/**
 * @file Mesh.h
 * @brief High-performance mesh container with fields as primary storage
 * 
 * This class serves as the central container for simulation data,
 * managing Field objects as the primary storage mechanism. Cells are
 * provided as an abstraction layer for accessing field data in the
 * context of the mesh structure and neighbor relationships.
 * 
 * Field Access Strategy:
 * ----------------------
 * The design supports efficient field access patterns:
 * 
 * 1. Direct Field Access: Fields are stored as member variables in the specialized
 *    Mesh classes and exposed through accessor methods that return references.
 * 
 * 2. Generated Cell Access: Code-generated Cell subclasses directly access these
 *    fields via the accessor methods, without virtual calls in the inner loop.
 * 
 * 3. Type Safety: All field access is strongly typed at compile time.
 */

#ifndef MESH_H
#define MESH_H

#include "MeshBase.h"
#include "Field.h"
#include "CellBase.h"
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>
#include <cstdint>

/**
 * @brief Base type for region identifiers
 * 
 * Specific values will be generated by the code generator
 */
using RegionID = uint32_t;

/**
 * @brief Base type for field identifiers
 * 
 * Specific values will be generated by the code generator
 */
using FieldID = uint32_t;

/**
 * @brief Bit mask type for region selection
 */
using RegionMask = uint64_t;

/**
 * @brief Bit mask type for field selection
 */
using FieldMask = uint64_t;

/**
 * @class Mesh
 * @brief Central container for field data with cell-based access abstraction
 * 
 * The Mesh class manages field data as its primary storage and provides
 * cell objects as a convenient abstraction for accessing that data. This
 * design allows for efficient memory layout in fields while providing
 * the logical organization of cells.
 * 
 * @tparam CellType The specialized Cell type to use for access abstraction
 */
template <typename CellType>
class Mesh : public MeshBase {
public:
    /**
     * @brief Construct a new Mesh object
     * 
     * @param nx Number of cells in x-direction
     * @param ny Number of cells in y-direction
     * @param dx Physical size of each cell in x-direction
     * @param dy Physical size of each cell in y-direction
     * @param originX X-coordinate of the origin (lower-left corner)
     * @param originY Y-coordinate of the origin (lower-left corner)
     */
    Mesh(int nx, int ny, double dx = 1.0, double dy = 1.0, 
         double originX = 0.0, double originY = 0.0);
    
    /**
     * @brief Virtual destructor
     */
    virtual ~Mesh() = default;
    
    /**
     * @brief Get physical dimensions of the mesh
     * 
     * @return std::pair<double, double> Physical width and height
     */
    std::pair<double, double> getPhysicalDimensions() const;
    
    /**
     * @brief Get physical coordinates from cell indices
     * 
     * @param i Index in x-direction
     * @param j Index in y-direction
     * @return std::pair<double, double> Physical (x,y) coordinates
     */
    std::pair<double, double> cellToPhysical(int i, int j) const;
    
    /**
     * @brief Get cell indices from physical coordinates
     * 
     * @param x Physical x-coordinate
     * @param y Physical y-coordinate
     * @return std::pair<int, int> Cell indices (i,j)
     */
    std::pair<int, int> physicalToCell(double x, double y) const;
    
    /**
     * @brief Get cell at specified indices with static typing
     * 
     * @param i Index in x-direction
     * @param j Index in y-direction
     * @return CellBase* Pointer to cell as base type (nullptr if out of bounds)
     * 
     * @note This implementation returns CellBase* to satisfy the MeshBase interface.
     *       Specialized subclasses should override and return the concrete cell type.
     */
    CellBase* getCell(int i, int j) override;
    
    /**
     * @brief Get typed cell at specified indices
     * 
     * @param i Index in x-direction
     * @param j Index in y-direction
     * @return CellType* Typed pointer to cell (nullptr if out of bounds)
     * 
     * @note This method returns the concrete cell type and should be used
     *       when the caller knows the specific mesh type.
     */
    CellType* getTypedCell(int i, int j);
    
    /**
     * @brief Get neighboring cell with static typing
     * 
     * @param i Current cell's i-index
     * @param j Current cell's j-index
     * @param direction Direction to neighbor (using CellBase direction constants)
     * @return CellType* Pointer to neighbor (nullptr if out of bounds)
     */
    CellType* getNeighborCell(int i, int j, uint8_t direction) const;
    
    /**
     * @brief Create a new field with specified parameters
     * 
     * @tparam T Field data type
     * @tparam LocationTag Field location tag
     * @param fieldID Field identifier
     * @param name Field name for debugging/serialization
     * @param defaultValue Optional default value
     * @return Field<T, LocationTag>& Reference to the created field
     * 
     * @note This is primarily used during mesh initialization or simulation setup.
     *       In generated code, fields will typically be direct member variables.
     */
    template <typename T, typename LocationTag>
    Field<T, LocationTag>& createField(FieldID fieldID, 
                                       const std::string& name = "",
                                       const T& defaultValue = T());
    
    /**
     * @brief Access an existing field by ID
     * 
     * @tparam T Field data type
     * @tparam LocationTag Field location tag
     * @param fieldID Field identifier
     * @return Field<T, LocationTag>& Reference to the field
     * @throws std::runtime_error if field doesn't exist or type mismatch
     * 
     * @note In generated code, specialized accessor methods will be provided
     *       for each field (e.g., pressureField(), temperatureField()).
     */
    template <typename T, typename LocationTag>
    Field<T, LocationTag>& getField(FieldID fieldID);
    
    /**
     * @brief Const access to an existing field by ID
     * 
     * @tparam T Field data type
     * @tparam LocationTag Field location tag
     * @param fieldID Field identifier
     * @return const Field<T, LocationTag>& Const reference to the field
     * @throws std::runtime_error if field doesn't exist or type mismatch
     */
    template <typename T, typename LocationTag>
    const Field<T, LocationTag>& getField(FieldID fieldID) const;
    
    /**
     * @brief Check if a field exists
     * 
     * @param fieldID Field identifier
     * @return true If field exists
     * @return false If field doesn't exist
     */
    bool hasField(FieldID fieldID) const;
    
    /**
     * @brief Get the origin coordinates
     * 
     * @return std::pair<double, double> The (x,y) coordinates of the origin
     */
    std::pair<double, double> getOrigin() const;
    
    /**
     * @brief Get the field mask for a field ID
     * 
     * @param fieldID Field identifier
     * @return FieldMask Bit mask for the field
     */
    FieldMask getFieldMask(FieldID fieldID) const;
    
    /**
     * @brief Get the region mask for a region ID
     * 
     * @param regionID Region identifier
     * @return RegionMask Bit mask for the region
     */
    RegionMask getRegionMask(RegionID regionID) const;

protected:
    /** Storage for cells with strong typing */
    std::vector<CellType> m_cells;
    
    /** Physical origin of the mesh (lower-left corner) */
    double m_originX, m_originY;
    
    /** Structure to store field information */
    struct FieldEntry {
        void* fieldPtr;
        std::string typeName;
        std::string name;
        size_t elemSize;
        FieldMask mask;
        
        // Destructor to properly clean up the type-erased field
        ~FieldEntry();
    };
    
    /** Map of field IDs to field entries */
    std::unordered_map<FieldID, std::unique_ptr<FieldEntry>> m_fields;
    
    /** Map of region IDs to region masks */
    std::unordered_map<RegionID, RegionMask> m_regionMasks;
    
    /**
     * @brief Type checking for field access
     * 
     * @tparam T Field data type
     * @tparam LocationTag Field location tag
     * @param entry Field entry to check
     * @return true If types match
     * @return false If types don't match
     */
    template <typename T, typename LocationTag>
    bool validateFieldType(const FieldEntry* entry) const;
    
    /**
     * @brief Friend declaration for CellType
     * 
     * This allows the specialized Cell type to access protected
     * members of the Mesh, which is crucial for direct field access.
     */
    friend CellType;
};

#include "Mesh.hpp"  // Template implementation

#endif // MESH_H
 
