/**
 * @file MeshBase.h
 * @brief Base class for mesh containers with abstract cell access
 * 
 * Design Agenda:
 * --------------
 * This abstract base class provides common functionality for all mesh types, including:
 * 
 * 1. Grid dimensions and physical properties
 * 2. Abstract cell access interface
 * 3. Index conversion utilities
 * 
 * Field Access Strategy:
 * ----------------------
 * MeshBase is designed to work with a code generation system where:
 * 1. Specialized Mesh subclasses store field data directly as member variables
 * 2. Generated Cell subclasses access these fields through direct member access
 * 3. No virtual function calls or string lookups are needed in the inner loop
 * 
 * This design prioritizes performance while maintaining a clean interface.
 */

#ifndef MESH_BASE_H
#define MESH_BASE_H

#include <utility>
#include <cstdint>
#include <stdexcept>

// Forward declarations
class CellBase;

/**
 * @class MeshBase
 * @brief Abstract base class for mesh containers
 * 
 * Provides common functionality and interface for all mesh types.
 * Concrete implementations will be generated by the code generator.
 */
class MeshBase {
public:
    /**
     * @brief Construct a new Mesh Base object
     * 
     * @param nx Number of cells in x-direction
     * @param ny Number of cells in y-direction
     * @param dx Grid spacing in x-direction (physical units)
     * @param dy Grid spacing in y-direction (physical units)
     */
    MeshBase(int nx, int ny, double dx, double dy);
    
    /**
     * @brief Virtual destructor
     */
    virtual ~MeshBase() = default;
    
    /**
     * @brief Get the number of cells in the x-direction
     * 
     * @return int Number of cells in x-direction
     */
    int nx() const { return m_nx; }
    
    /**
     * @brief Get the number of cells in the y-direction
     * 
     * @return int Number of cells in y-direction
     */
    int ny() const { return m_ny; }
    
    /**
     * @brief Get the grid spacing in the x-direction
     * 
     * @return double Grid spacing in x-direction (physical units)
     */
    double dx() const { return m_dx; }
    
    /**
     * @brief Get the grid spacing in the y-direction
     * 
     * @return double Grid spacing in y-direction (physical units)
     */
    double dy() const { return m_dy; }
    
    /**
     * @brief Get cell at specified indices
     * 
     * @param i Index in x-direction
     * @param j Index in y-direction
     * @return CellBase* Pointer to cell (nullptr if out of bounds)
     * 
     * @note In generated subclasses, this will be overridden to return
     *       the specific Cell type for that mesh (e.g., FluidCell* for FluidMesh)
     */
    virtual CellBase* getCell(int i, int j) = 0;
    
    /**
     * @brief Convert 2D indices to linear index
     * 
     * @param i Index in x-direction
     * @param j Index in y-direction
     * @return int Linear index
     */
    int linearIndex(int i, int j) const {
        return i + j * m_nx;
    }
    
    /**
     * @brief Convert linear index to 2D indices
     * 
     * @param linearIdx Linear index
     * @return std::pair<int, int> (i,j) indices
     */
    std::pair<int, int> toIndices(int linearIdx) const {
        int j = linearIdx / m_nx;
        int i = linearIdx % m_nx;
        return {i, j};
    }
    
    /**
     * @brief Get physical position of cell center from indices
     * 
     * @param i Index in x-direction
     * @param j Index in y-direction
     * @return std::pair<double, double> (x,y) position in physical units
     */
    std::pair<double, double> position(int i, int j) const {
        return {i * m_dx, j * m_dy};
    }

protected:
    int m_nx;    ///< Number of cells in x-direction
    int m_ny;    ///< Number of cells in y-direction
    double m_dx; ///< Grid spacing in x-direction (physical units)
    double m_dy; ///< Grid spacing in y-direction (physical units)
    
    /**
     * @brief Friend declaration for CellBase
     * 
     * This allows CellBase and its descendants to access protected
     * members of MeshBase and its descendants. This is crucial for
     * enabling efficient field access in generated code.
     */
    friend class CellBase;
};

#endif // MESH_BASE_H


